/* ══════════════════════════════════════════════════════
   Alterity Labs — Video Config
   Auto-generated by the Dashboard. Do not edit manually.
   Last updated: 2026-04-23T15:57:37.478Z
══════════════════════════════════════════════════════ */

const INSTAGRAM_CONFIG = {

  showreelPosts: [
    {
      url:   'https://www.instagram.com/p/Cwkc0yTIPjw/',
      label: 'Video Editing — Reels, Shorts, YouTube & Ads',
      tag:   '01',
      time:  '00:00',
    },
    {
      url:   'https://youtu.be/q65qouS4WFE',
      label: 'Creative Support — Design, Branding & Content',
      tag:   '02',
      time:  '00:06',
    },
    {
      url:   'https://youtu.be/tVlIfKXirM4',
      label: 'Digital Development — Websites & Web Applications',
      tag:   '03',
      time:  '00:12',
    },
    {
      url:   'https://youtu.be/OVOK30QX9vE',
      label: 'Mobile Solutions — Apps for iOS & Android',
      tag:   '04',
      time:  '00:18',
    },
    {
      url:   'https://youtu.be/XajFZTc0-Aw',
      label: 'Results — Brands That Engage, Grow & Scale Online',
      tag:   '05',
      time:  '00:24',
    }
  ],

  projects: [
    {
      id:         'card-1',
      postUrl:    'https://youtu.be/F8xrXDK0KLY',
      previewUrl: 'https://youtu.be/F8xrXDK0KLY',
    },
    {
      id:         'card-2',
      postUrl:    'https://youtube.com/shorts/KviuLIzpcuw?feature=share',
      previewUrl: 'https://youtube.com/shorts/KviuLIzpcuw?feature=share',
    },
    {
      id:         'card-3',
      postUrl:    'https://youtube.com/shorts/Z-CTgL7zLmI?feature=share',
      previewUrl: 'https://youtube.com/shorts/Z-CTgL7zLmI?feature=share',
    },
    {
      id:         'card-4',
      postUrl:    'https://youtu.be/HARO2svqDBg',
      previewUrl: 'https://youtu.be/HARO2svqDBg',
    },
    {
      id:         'card-5',
      postUrl:    'https://youtube.com/shorts/o_oLCws_Eus?feature=share',
      previewUrl: 'https://youtube.com/shorts/o_oLCws_Eus?feature=share',
    },
    {
      id:         'card-6',
      postUrl:    'https://www.youtube.com/watch?v=80GJT_5TfY0',
      previewUrl: 'https://www.youtube.com/watch?v=80GJT_5TfY0',
    }
  ],

  profileUrl: 'https://www.instagram.com/portfolio.showcase/',
};
