/* ══════════════════════════════════════════════════════
   Alterity Labs — Video Config
   Auto-generated by the Dashboard. Do not edit manually.
   Last updated: 2026-04-22T20:35:17.591Z
══════════════════════════════════════════════════════ */

const INSTAGRAM_CONFIG = {

  showreelPosts: [
    {
      url:   'https://www.instagram.com/p/Cwkc0yTIPjw/',
      label: 'Video Editing — Reels, Shorts, YouTube & Ads',
      tag:   '01',
      time:  '00:00',
    },
    {
      url:   '',
      label: 'Creative Support — Design, Branding & Content',
      tag:   '02',
      time:  '00:06',
    },
    {
      url:   '',
      label: 'Digital Development — Websites & Web Applications',
      tag:   '03',
      time:  '00:12',
    },
    {
      url:   '',
      label: 'Mobile Solutions — Apps for iOS & Android',
      tag:   '04',
      time:  '00:18',
    },
    {
      url:   '',
      label: 'Results — Brands That Engage, Grow & Scale Online',
      tag:   '05',
      time:  '00:24',
    }
  ],

  projects: [
    {
      id:         'card-1',
      postUrl:    '',
      previewUrl: '',
    },
    {
      id:         'card-2',
      postUrl:    '',
      previewUrl: '',
    },
    {
      id:         'card-3',
      postUrl:    '',
      previewUrl: '',
    },
    {
      id:         'card-4',
      postUrl:    '',
      previewUrl: '',
    },
    {
      id:         'card-5',
      postUrl:    '',
      previewUrl: '',
    },
    {
      id:         'card-6',
      postUrl:    '',
      previewUrl: '',
    }
  ],

  profileUrl: 'https://www.instagram.com/portfolio.showcase/',
};
